### ISSUE TITLE
Error durante modificación de fondo de pantalla - No resuelve install.flisolcaba.net

### ISSUE THREAD

**Issue by fefulowe** [FlisolCaba/postinstall#5]
Probamos el script en una instalación limpia de ubuntu-mate-16.04.2-desktop-amd64.iso . El programa se ejecuta correctamente. El navegador abre el navegador en la página web de fondos de pantalla[2] con error (porque no resuelve el nombre) y otra pestaña con el sistema eventol (la cual abre correctamente).

Supongo que la resolución del nombre install.flisolcaba.net será resuelta de manera local por el servidor de nombres local. Probablemente convenga mover los archivos directamente al repositorio git y descargarlos desde allí en caso de que el nombre del servidor local no se pueda resolver correctamente.

[1] ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for vlc-nox (2.2.2-5ubuntu0.16.04.1) ...
Processing triggers for resolvconf (1.78ubuntu4) ...
-----------------------------------------------------------------------
*** Registrando instalacion...
Vamos a registrar la instalacion en eventoL, que es nuestro sistema libre para administracion de eventos (disponible en https://github.com/GNUtn/eventoL). A continuacion se abrira el navegador con la pagina del evento.
Para registrar la instalacion, siga estos pasos:
 1- Pidale al instalador que inicie sesion con su usuario.
 2- Registre la instalacion en Colaboradores > Cargar una instalacion.
 3- Complete los campos indicados.

Si no se encuentra registrado, debe crear una cuenta en la seccion Iniciar sesion y luego en Registrarme.

Al terminar, podra continuar la ejecucion de este script.

Registre la instalacion, lo espero...
**? Presione cualquier tecla para continuar...ERROR - ContextualIdentityService - Unknown version found in /home/test/.mozilla/firefox/7ctelnwk.default/containers.json
1492644585786	addons.update-checker	WARN	Update manifest for aushelper@mozilla.org did not contain an updates property
1492644585965	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property
1492644586294	addons.update-checker	WARN	Update manifest for webcompat@mozilla.org did not contain an updates property
1492644586308	addons.update-checker	WARN	Update manifest for firefox@getpocket.com did not contain an updates property
1492644586317	addons.update-checker	WARN	Update manifest for e10srollout@mozilla.org did not contain an updates property
1492644586385	addons.update-checker	WARN	Update manifest for deployment-checker@mozilla.org did not contain an updates property

-----------------------------------------------------------------------
*** Cambiando fondo de pantalla...
Le ofrecemos fondos de pantalla para su sistema.
Si desea descargarlos y/o ver los disponibles, dirijase a
http://install.flisolcaba.net/postinstall/wallpaper
**? Presione cualquier tecla para continuar...
-----------------------------------------------------------------------
Hemos terminado :)
No fue tan dificil, no?

Ahora si, lo dejamos con su sistema para que lo disfrute, cualquier duda que tenga acerquese a uno de los instaladores o revise las opciones de contacto en nuestra web: http://cafelug.org.ar

Un abrazo grande,
- El equipo de FLISoL CABA

[2] http://install.flisolcaba.net/postinstall/wallpapers.html

**Comment by HacKanCuBa** [comment]
Sí, la url install.flisolcaba.net solo resuelve el día del flisol. Aun no hemos definido repo ni url que resuelva fuera del mismo. De hecho, tampoco tenemos wallpapers por ofrecer, asi que esa url mostrara lo siguiente: http://flisolcaba.github.io/install-web/postinstall/wallpaper/
Esa parte del script no es muy util en este momento. A futuro la idea seria que el mismo script instale el wallpaper automaticamente luego de ser elegido, pero la gran cant de escritorios lo transforma en una tarea mas q ardua.
